<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\Identity\MonolithTemplate.Identity.Contracts\MonolithTemplate.Identity.Contracts.csproj" />
    <ProjectReference Include="..\MonolithTemplate.Notifications.Domain\MonolithTemplate.Notifications.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="EmailSender\" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
