<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Responses\**" />
    <EmbeddedResource Remove="Responses\**" />
    <None Remove="Responses\**" />
  </ItemGroup>

   <ItemGroup>
     <Folder Include="Endpoints\" />
   </ItemGroup>

   <ItemGroup>
     <ProjectReference Include="..\..\..\MonolithTemplate.Shared\MonolithTemplate.Shared.csproj" />
     <ProjectReference Include="..\MonolithTemplate.Identity.Application\MonolithTemplate.Identity.Application.csproj" />
   </ItemGroup>

</Project>
